### ISSUE TITLE
Are defaults set in the code?

### ISSUE THREAD

**Issue by dadamsGS** [buildsville/list-pull-requests#7]
@buildsville When I run a job like this
```
  publish_pull_requests_to_slack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get List of Open Pull Requests
      uses: buildsville/list-pull-requests@v1.0.1
      id: list
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: output
      run: echo '${{ steps.list.outputs.pulls }}'
```

The job output is always:
```
Run buildsville/list-pull-requests@v1.0.1
  with:
    token: ***
    labels: [ "WFR" ]
    skip_hour: 24
```
```
Run echo ''
  echo ''
  shell: /usr/bin/bash -e {0}
```

Is there something I am missing? My project does not use any labels and I want to get all of the PRs, not filtered.

**Comment by buildsville** [comment]
Hi, @dadamsGS 😃 

Defaults are set in [action.yml](https://github.com/buildsville/list-pull-requests/blob/master/action.yml) .

Aside from the good and bad of these defaults, you can get all the PRs by

```
  publish_pull_requests_to_slack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get List of Open Pull Requests
      uses: buildsville/list-pull-requests@v1.0.1
      id: list
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        labels: '[]'  # <- add this line
        skip_hour: '0'  # <- add this line
    - name: output
      run: echo '${{ steps.list.outputs.pulls }}'
```

Thank you !

**Comment by dadamsGS** [comment]
Thanks so much, @buildsville !

I am a (seemingly constant) GH Actions newbie.

I was (kind of) close with...
```
- name: Get List of Open Pull Requests
      uses: buildsville/list-pull-requests@v1.0.1
      id: list
      with:
        labels: ''
        token: ${{secrets.GITHUB_TOKEN}}
```

I also tried:
```
labels: '[*]'
```

Thanks for the response!
